<script setup lang="ts">
import { ref, onMounted } from 'vue'

import Founder from './components/Founder.vue'
import Cagr from './components/Cagr.vue'
import EquityCurve from './components/EquityCurve.vue'
import ReturnsOverview from './components/ReturnsOverview.vue'
import FinalQuote from './components/FinalQuote.vue'
import ShowInterest from './components/ShowInterest.vue'
import LandingView from './components/LandingView.vue'

interface Stats {
  'cagr_usdt_before_june2024_%': number
  'cagr_usdt_after_june2024_%': number
}

const cagrBefore = ref<number | null>(null)
const cagrAfter = ref<number | null>(null)


onMounted(async () => {
  try {
    const res = await fetch('/stats.json')
    if (!res.ok) throw new Error('Failed to load stats.json')

    const data: Stats = await res.json()
    cagrBefore.value = data['cagr_usdt_before_june2024_%']
    cagrAfter.value = data['cagr_usdt_after_june2024_%']
  } catch (error) {
    console.error(error)
  }
})
</script>

<template>
  <LandingView></LandingView>
  <div class="background">
    <div class="card-layout">
      <Cagr :cagr-before="cagrBefore" :cagr-after="cagrAfter"  />
      <Founder />
    </div>
    <EquityCurve></EquityCurve>
    <ReturnsOverview metric="usdt">
      <p>
        This table presents the <strong>impressive</strong> historical returns in terms of <strong>USD</strong>,
        both back-tested and real world results.
        <br><br>
        The strategy was deployed in the real world at the beginning of <strong>June 2024</strong>.
        The strategy behind these returns relies on <strong>early</strong> identification of trends within the market, and closing positions
        <strong>quickly</strong> when the market goes against it.

        <br><br>

        The strategy is <strong>fully automated</strong> and strictly trades <strong>cryptocurrencies</strong>.
        It thrives in <strong>volatile</strong> markets,
        which cryptocurrency markets certainly are.
        <br><br>
      </p>
    </ReturnsOverview>
    <div class="card-layout"></div>
    <ReturnsOverview metric="btc">
      <p>
        This table displays the historical returns generated by the trading strategy in terms of <strong>Bitcoin</strong>.
        <br><br>

        It is built on the <strong>core belief</strong> that accumulating more Bitcoin over time is a powerful path to
        long-term wealth. The strategy involves <strong>increasing Bitcoin holdings</strong> by trading other cryptocurrencies
        <br><br>
        Combining increased Bitcoin holdings with a rise in Bitcoin's USD price results in <strong>exponential
        growth</strong> during bull markets and helps <strong>mitigate losses</strong> during bear markets.

<!--        Over the long run, this approach significantly outperforms <strong>traditional</strong> investment methods.-->
      </p>


    </ReturnsOverview>
    <div class="card-layout"></div>

    <div class="card-layout">
      <FinalQuote></FinalQuote>
      <ShowInterest></ShowInterest>
    </div>

  </div>
</template>


<style scoped>
.background {
  min-height: 100vh;
  background:
      radial-gradient(circle at 30% 40%, rgba(50, 119, 245, 0.5), transparent 90%),
      radial-gradient(circle at 70% 60%, rgba(180, 240, 230, 0.4), transparent 90%);
  background-repeat: no-repeat;
  background-size: cover;
}


</style>



