<script setup lang="ts">
import Founder from "./components/Founder.vue";
import Cagr from "./components/Cagr.vue";
import EquityCurve from "./components/EquityCurve.vue";
import ReturnsOverview from "./components/ReturnsOverview.vue";
import FinalQuote from "./components/FinalQuote.vue";
import ShowInterest from "./components/ShowInterest.vue";
import LandingView from "./components/LandingView.vue";
</script>

<template>
  <LandingView></LandingView>
  <div class="background">
    <div class="card-layout">
      <Cagr />
      <Founder />
    </div>
    <ReturnsOverview metric="btc">
      <p>
        This table displays the historical returns generated by the trading strategy in terms of <strong>Bitcoin</strong>.
        The strategy was deployed in the real world at the beginning of <strong>June 2024</strong>.<br><br>
        It is built on the <strong>core belief</strong> that accumulating more Bitcoin over time is a powerful path to long-term wealth.<br><br>
        Combining increased Bitcoin holdings with a rise in Bitcoin's USD price results in <strong>exponential growth</strong> during bull markets and helps <strong>mitigate losses</strong> during bear markets.<br><br>
        Over the long run, this approach significantly outperforms <strong>traditional</strong> investment methods.
      </p>


    </ReturnsOverview>
    <div class="card-layout"></div>
    <ReturnsOverview metric="usdt">
      <p>
        This second table presents historical returns in terms of <strong>USDT</strong>, which is ultimately what matters most to investors.
        While the trading strategy isn't explicitly optimized for USDT returns, the results shown are nonetheless impressive.<br><br>
        <strong>Substantial risk appetite</strong> is a key requirement for those considering this fund, as it aims to deliver <strong>tremendous returns</strong>.<br>
        The strategy is designed to capture <strong>extraordinary gains</strong> that more than offset any losing trades.<br><br>
        Operating strictly within the crypto market and being <strong>fully automated</strong>, the strategy is built to detect major market moves early and exit quickly with minimal losses if the trend goes against it.<br><br>
        As such, this fund <strong>thrives in volatility</strong>—a defining characteristic of the crypto market.
      </p>

    </ReturnsOverview>
    <div class="card-layout"></div>
    <EquityCurve></EquityCurve>
    <div class="card-layout">
      <FinalQuote></FinalQuote>
      <ShowInterest></ShowInterest>
    </div>

  </div>
</template>


<style scoped>
.background {
  background: linear-gradient(
      135deg,
      #0f2027 0%,    /* very dark blue */
      #203a43 30%,   /* medium dark blue */
      #2c5364 60%,   /* steel blue */
      #4a7587 90%    /* lighter blue */
  );
  min-height: 100vh;
}
</style>
