name: Deploy Vue3 + Vite to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: pages-artifact
    steps:
      # 1. Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build project
      - name: Build project
        run: npm run build

      # 5. Upload built site as Pages artifact (v4)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
          artifact_name: pages-artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 6. Deploy artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: ${{ needs.build.outputs.artifact_name }}
